[project]
name = "p-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "litellm>=1.96.0",
    "pandasai>=3.0.0",
    "pandasai-litellm>=0.0.1",
    "pandasai-sql[sqlserver]>=0.1.7",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "streamlit>=1.60.0",
]
